// Package report writes the release pull request's description blocks, which follow the
// release from the pull request's checks through publication: a summary at the start, which
// says what merging does and then what it did, and a status at the end, with the jobs and
// assets. When a merged release fails, it also writes a comment that tells whoever merged it.
package report

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/url"
	"regexp"
	"slices"
	"strings"

	"github.com/fabricahq/release-planner/internal/notes"
	"github.com/fabricahq/release-planner/internal/plan"
	"github.com/fabricahq/release-planner/internal/publish"
)

// The markers delimit the two blocks the Release workflow owns in a pull request's
// description: the summary at the start and the status at the end. Each report rewrites what
// is between them; the text around them, such as the agent's reason for the version, is left alone.
const (
	SummaryStart = "<!-- release-planner:summary:start -->"
	SummaryEnd   = "<!-- release-planner:summary:end -->"
	StatusStart  = "<!-- release-planner:status:start -->"
	StatusEnd    = "<!-- release-planner:status:end -->"

	// Credit closes the status block. GitHub renders a blockquote in muted gray, so it's quiet.
	Credit = "\n> Generated by [Release Planner](https://release-planner.fabricahq.com)\n"
)

// Job is one Release workflow job's result and outputs, as the workflow's needs context has them.
type Job struct {
	Result  string            `json:"result"`
	Outputs map[string]string `json:"outputs"`
}

// EditedNotes is one entry of the publish job's notes output, a JSON list: whether publishing
// changed the notes of a release the plan edits.
type EditedNotes struct {
	Tag     string `json:"tag"`
	Changed bool   `json:"changed"`
}

// Asset is a built release file.
type Asset struct {
	Name string
	Size int64
}

// Status is everything the description's blocks describe.
type Status struct {
	// Server is the GitHub URL, such as https://github.com, and Repository the owner/name.
	Server, Repository string
	RunURL             string
	// RunID and RunAttempt identify the workflow run attempt that reports.
	RunID, RunAttempt string
	// Branch is the release branch. Before the merge, HeadRef is the pull request's branch, in
	// HeadRepository, or in Repository when that is "".
	Branch, HeadRef, HeadRepository string
	// Merged is true after the pull request merged, in the run that publishes.
	Merged bool
	// Plan is the validated plan, or nil when validation failed before writing one.
	Plan *plan.Plan
	Jobs map[string]Job
	// RunJobs are this run's jobs and BuildJobs those of the pull request's run, when the
	// release reuses it, for linking each job. Either may be missing.
	RunJobs, BuildJobs []publish.RunJob
	// BuildsAssets is true when the repository configures release assets.
	BuildsAssets bool
	Assets       []Asset
	// Archive is the URL of the release-assets workflow artifact, a zip of the assets, or ""
	// when it's unknown.
	Archive  string
	MergedBy string
	// Hooks are the workflows the Release workflow runs around the release, each in its own job.
	Hooks []Hook
}

// Hook is a workflow the Release workflow runs around a release, in a job of its own: one of
// the repository's own, or a workflow in another repository it starts.
type Hook struct {
	// Job is the job's ID, and Name its name, such as "pre-publish (migrate-database.yml)".
	Job  string `json:"job"`
	Name string `json:"name"`
	// When is "pre-publish" or "post-publish".
	When string `json:"when"`
	// Workflow is the workflow's file name, in Repository when it's in another repository.
	Workflow   string `json:"workflow"`
	Repository string `json:"repository,omitempty"`
	// Title is the name the workflow declares, or "" when it declares none.
	Title string `json:"title,omitempty"`
	// Prereleases is true when a post-publish workflow also runs for prereleases.
	Prereleases bool `json:"prereleases,omitempty"`
}

// title is the hook's display name: the name its workflow declares, or its file name, after
// its repository when that's another one.
func (h Hook) title() string {
	switch {
	case h.Repository != "":
		return markdownText(h.Repository) + " `" + h.Workflow + "`"
	case h.Title != "":
		return markdownText(h.Title)
	}
	return "`" + h.Workflow + "`"
}

// named is true when the hook's display name is the name its workflow declares.
func (h Hook) named() bool { return h.Repository == "" && h.Title != "" }

// label names the hook in its row of the jobs table: by its name, or by what it runs.
func (h Hook) label() string {
	if h.named() {
		return h.title()
	}
	return "Run " + h.title()
}

// mention names the hook in a sentence: its name in bold, or what it runs.
func (h Hook) mention() string {
	if h.named() {
		return "**" + h.title() + "**"
	}
	return h.title()
}

// Blocks are the contents of the description's summary and status blocks, without their markers.
type Blocks struct{ Summary, Status string }

// jobs are the Release workflow's jobs, in the order they run.
var jobs = []struct{ id, label string }{
	{"validate", "Check the version and release notes"},
	{"release-checks", "Run the release checks"},
	{"release-assets", "Build the release assets"},
	{"attest", "Attest the release assets"},
	{"publish", "Publish"},
	{"attest-release", "Attest the published assets"},
}

var icons = map[string]string{"success": "✅", "failure": "❌", "cancelled": "⚪"}

// row is one job of the Release workflow, in the jobs table: a fixed job, or a hook's.
type row struct {
	id, label string
	hook      *Hook
}

// order lists the Release workflow's jobs in the order they run: the pre-publish hooks run
// before publish, and the post-publish hooks after the published assets are attested.
func (s Status) order() []row {
	var rows []row
	hooks := func(when string) {
		for i := range s.Hooks {
			if h := &s.Hooks[i]; h.When == when {
				rows = append(rows, row{h.Job, h.label(), h})
			}
		}
	}
	for _, j := range jobs {
		if j.id == "publish" {
			hooks("pre-publish")
		}
		rows = append(rows, row{j.id, j.label, nil})
	}
	hooks("post-publish")
	return rows
}

// hooks lists the hooks that run when, pre-publish or post-publish.
func (s Status) hooks(when string) []Hook {
	var list []Hook
	for _, h := range s.Hooks {
		if h.When == when {
			list = append(list, h)
		}
	}
	return list
}

// hook returns the hook the job runs, or nil.
func (s Status) hook(job string) *Hook {
	for i := range s.Hooks {
		if s.Hooks[i].Job == job {
			return &s.Hooks[i]
		}
	}
	return nil
}

// failures lists the Release workflow's jobs that failed or were cancelled, in the order they run.
func (s Status) failures() []row {
	var rows []row
	for _, j := range s.order() {
		if r := s.Jobs[j.id].Result; r == "failure" || r == "cancelled" {
			rows = append(rows, j)
		}
	}
	return rows
}

// Failed returns the first Release workflow job that failed or was cancelled, or "".
func (s Status) Failed() string {
	if rows := s.failures(); len(rows) > 0 {
		return rows[0].id
	}
	return ""
}

// failedJobs says which jobs failed and which were cancelled, in a clause for each, such as
// "The Deploy and o/tap `update.yml` jobs failed" and "the publish job was cancelled". It
// names a hook's job by the hook's display name, as the jobs table does, and any other job by
// its ID, each through emphasize. The first clause starts with the determiner first.
func (s Status) failedJobs(first string, emphasize func(string) string) []string {
	var clauses []string
	for _, result := range []string{"failure", "cancelled"} {
		var names []string
		for _, j := range s.failures() {
			if s.Jobs[j.id].Result != result {
				continue
			}
			name := j.id
			if j.hook != nil {
				name = j.hook.title()
			}
			names = append(names, emphasize(name))
		}
		if len(names) == 0 {
			continue
		}
		determiner := "the"
		if len(clauses) == 0 {
			determiner = first
		}
		verb := "failed"
		switch {
		case result == "cancelled" && len(names) == 1:
			verb = "was cancelled"
		case result == "cancelled":
			verb = "were cancelled"
		}
		clauses = append(clauses, fmt.Sprintf("%s %s %s %s", determiner, list(names), plural(len(names), "job"), verb))
	}
	return clauses
}

// list joins names into a list such as "a, b, and c".
func list(names []string) string {
	switch len(names) {
	case 0:
		return ""
	case 1:
		return names[0]
	case 2:
		return names[0] + " and " + names[1]
	}
	return strings.Join(names[:len(names)-1], ", ") + ", and " + names[len(names)-1]
}

func plain(name string) string { return name }

func bold(name string) string { return "**" + name + "**" }

// markdownText escapes text so Markdown shows it as written, even in a table cell.
func markdownText(s string) string {
	return markdownSpecial.ReplaceAllString(s, `\$0`)
}

var markdownSpecial = regexp.MustCompile("[\\\\`*_~\\[\\]<>|#]")

// PrePublishDocs explains what to do when the pre-publish workflow fails.
const PrePublishDocs = "https://release-planner.fabricahq.com/customize/pre-publish/#if-it-fails"

// stopped explains a run after the merge that stopped on purpose, or failed in a way with its
// own remedy, or returns "".
func (s Status) stopped(p *plan.Plan, failed string) string {
	validate, publish := s.Jobs["validate"].Outputs, s.Jobs["publish"].Outputs
	switch {
	case failed == "validate" && validate["waiting-for"] != "" && validate["waiting-for-file"] != "":
		tag := validate["waiting-for"]
		return fmt.Sprintf("⏳ **This release waits for %s,** which merged earlier and isn't published yet. Publish %s, or withdraw it by deleting `%s` in a pull request. Then use **Re-run failed jobs** on [this run](%s).", tag, tag, validate["waiting-for-file"], s.RunURL)
	case failed == "validate" && validate["waiting-for"] != "":
		tag := validate["waiting-for"]
		return fmt.Sprintf("⏳ **This release waits for %s,** which is tagged but has no published release. Publish %s by re-running its release run, then use **Re-run failed jobs** on [this run](%s). If %s's tag isn't on its release commit, delete the tag first.", tag, tag, s.RunURL, tag)
	case failed == "validate" && validate["withdrawn"] != "", failed == "publish" && publish["release"] == "withdrawn":
		return fmt.Sprintf("⚪ **A later change to the release notes on %s withdrew or replaced what this pull request approved,** so this run doesn't publish it. Any newer request publishes from its own run.", s.Branch)
	}
	if h := s.hook(failed); h != nil && h.When == "pre-publish" {
		// Pre-publish workflows run in parallel, once every job before them succeeded, so the
		// jobs that failed or were cancelled are all pre-publish workflows.
		what := strings.Join(s.failedJobs("The", plain), ", and ")
		if !slices.ContainsFunc(s.failures(), func(j row) bool { return s.Jobs[j.id].Result == "failure" }) {
			return fmt.Sprintf("⚪ **%s,** so this attempt stopped before publishing. Use **Re-run failed jobs** on [that run](%s).", what, s.RunURL)
		}
		return fmt.Sprintf("❌ **%s,** so this attempt stopped before publishing. See [the workflow run](%s). If the cause was outside the release commit, fix it, then use **Re-run failed jobs** on that run. If the release commit itself is broken, withdraw %s: delete `%s` in the pull request that fixes it, then release again. [What to do when pre-publish fails](%s)", what, s.RunURL, p.Tag, p.File, PrePublishDocs)
	}
	return ""
}

func (s Status) release(tag string) string {
	return fmt.Sprintf("[%s](%s/%s/releases/tag/%s)", tag, s.Server, s.Repository, tag)
}

// edit links to the page that edits a notes file: on the pull request's branch before the
// merge, and on the release branch after it, where saving starts a pull request that edits the
// published notes.
func (s Status) edit(tag, file string) string {
	repository, ref := s.Repository, s.Branch
	if !s.Merged && s.HeadRef != "" {
		ref = s.HeadRef
		if s.HeadRepository != "" {
			repository = s.HeadRepository
		}
	}
	return fmt.Sprintf("**[✏️ Edit the %s release notes](%s/%s/edit/%s/%s)**", tag, s.Server, repository, pathEscape(ref), pathEscape(file))
}

func pathEscape(p string) string {
	parts := strings.Split(p, "/")
	for i, part := range parts {
		parts[i] = url.PathEscape(part)
	}
	return strings.Join(parts, "/")
}

// Render writes the description's blocks, or returns empty blocks when there's nothing to
// report: the pull request requests no release and edits no notes, and nothing failed.
func Render(s Status) Blocks {
	p := s.Plan
	if s.Failed() == "" && (p == nil || p.Empty()) {
		return Blocks{}
	}
	return Blocks{Summary: s.summary(), Status: s.status() + Credit}
}

func (s Status) summary() string {
	var b strings.Builder
	line := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }
	p, failed := s.Plan, s.Failed()
	if p == nil {
		p = &plan.Plan{}
	}
	published := s.Jobs["publish"].Result == "success"

	// A withdrawn or replaced request's file is gone or changed on the release branch, so
	// there's nothing of this pull request's to edit.
	if s.Jobs["publish"].Outputs["release"] != "withdrawn" {
		if p.Tag != "" && p.File != "" {
			line("%s\n", s.edit(p.Tag, p.File))
		}
		for _, e := range p.Edits {
			line("%s\n", s.edit(e.Tag, e.File))
		}
	}

	failure := func(fix string) {
		if failed != "" {
			line("❌ **%s.** See [the workflow run](%s). %s\n", strings.Join(s.failedJobs("The", plain), ", and "), s.RunURL, fix)
		}
	}
	switch {
	case s.Merged:
		if published {
			outputs := s.Jobs["publish"].Outputs
			switch {
			case p.Tag != "" && outputs["release"] == "already-published":
				line("✅ %s was already published from `%s`.\n", s.release(p.Tag), short(p.Commit))
			case p.Tag != "":
				line("✅ Published %s from `%s`.\n", s.release(p.Tag), short(p.Commit))
			}
			// Without publish's notes output, as from an older run, an edit that succeeded updated them.
			var edited []EditedNotes
			_ = json.Unmarshal([]byte(outputs["notes"]), &edited)
			for _, e := range p.Edits {
				i := slices.IndexFunc(edited, func(x EditedNotes) bool { return x.Tag == e.Tag })
				if i >= 0 && !edited[i].Changed {
					line("✅ The notes of %s were already up to date.\n", s.release(e.Tag))
				} else {
					line("✅ Updated the notes of %s.\n", s.release(e.Tag))
				}
			}
		}
		if why := s.stopped(p, failed); why != "" {
			line("%s\n", why)
			break
		}
		failure("Once the cause is fixed, use **Re-run failed jobs** on that run. It uses the same release commit and files, and changes nothing that already succeeded.")
	default:
		failure("Fix the cause and push to this branch, and the checks run again. Nothing is published until this pull request merges.")
		if p.Empty() {
			break
		}
		line("**When you merge this PR:**")
		if pre := s.hooks("pre-publish"); p.Tag != "" && len(pre) == 1 {
			line("- First, %s runs on the release commit. If it fails, the release isn't published.", pre[0].mention())
		} else if p.Tag != "" && len(pre) > 1 {
			var names []string
			for _, h := range pre {
				names = append(names, h.mention())
			}
			line("- First, these run on the release commit, in parallel: %s. If any fails, the release isn't published.", strings.Join(names, ", "))
		}
		if p.Tag != "" {
			line("- The release commit, `%s`, is tagged `%s`.", short(p.Commit), p.Tag)
			files := ""
			switch {
			case len(s.Assets) > 0:
				files = " and the files listed below"
			case s.BuildsAssets:
				files = " and the release assets"
			}
			line("- The %s GitHub release is published with these release notes%s.", p.Tag, files)
			// Post-publish workflows skip prereleases unless they opt in.
			var names []string
			for _, h := range s.hooks("post-publish") {
				if !p.Prerelease || h.Prereleases {
					names = append(names, h.mention())
				}
			}
			switch len(names) {
			case 0:
			case 1:
				line("- Then %s runs.", names[0])
			default:
				line("- Then these run, in parallel: %s.", strings.Join(names, ", "))
			}
		}
		for _, e := range p.Edits {
			line("- The %s release notes on GitHub are replaced with `%s`. Its tag and files don't change.", e.Tag, e.File)
			if e.HandEdited {
				line("- ⚠️ Someone edited the %s notes on GitHub since they merged, so they differ from `%s` on the release branch. Merging replaces those edits.", e.Tag, e.File)
			}
		}
		line("- This description updates with a link to the release, and you're @mentioned if anything fails.\n")
	}

	if !p.Empty() {
		line("### Release status\n")
		if p.Tag != "" {
			version := "`" + p.Tag + "`"
			if p.Prerelease {
				version += " (prerelease)"
			}
			previous := "None"
			if p.Previous != "" {
				previous = s.release(p.Previous)
			}
			line("| Version | Release commit | Previous release |\n| --- | --- | --- |")
			line("| %s | [`%s`](%s/%s/commit/%s) | %s |\n", version, short(p.Commit), s.Server, s.Repository, p.Commit, previous)
		}
		if len(p.Edits) > 0 {
			line("| Version | Release notes file |\n| --- | --- |")
			for _, e := range p.Edits {
				line("| %s | `%s` |", s.release(e.Tag), e.File)
			}
		}
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}

func (s Status) status() string {
	var b strings.Builder
	line := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }
	p := s.Plan
	published := s.Jobs["publish"].Result == "success"
	warnings := 0
	if p != nil {
		warnings = len(p.Findings)
		for _, e := range p.Edits {
			warnings += len(e.Findings)
		}
	}

	var rows []string
	row := func(icon, label, cell string) {
		rows = append(rows, fmt.Sprintf("| %s | %s | %s |", icon, label, cell))
	}
	for _, j := range s.order() {
		result := s.Jobs[j.id].Result
		switch {
		case j.id == "publish" && !s.Merged && p != nil && !p.Empty(),
			j.hook != nil && j.hook.When == "pre-publish" && !s.Merged && p != nil && p.Tag != "":
			row("⏸️", j.label, "Runs when you merge")
		case result == "skipped" && p != nil && p.Reused && (j.id == "release-checks" || j.id == "release-assets" || j.id == "attest"):
			build := fmt.Sprintf("%s/%s/actions/runs/%d", s.Server, s.Repository, p.BuildRun)
			row("♻️", j.label, fmt.Sprintf("[Reused from the pull request](%s)", jobURL(s.BuildJobs, j.id, build)))
		case icons[result] != "":
			icon, label := icons[result], j.label
			if j.id == "validate" && warnings > 0 {
				label += fmt.Sprintf(" (%d %s)", warnings, plural(warnings, "warning"))
				if result == "success" {
					icon = "⚠️"
				}
			}
			name := j.id
			if j.hook != nil {
				name = j.hook.Name
			}
			row(icon, label, s.details(s.RunJobs, name, s.RunURL))
		}
	}
	if len(rows) > 0 {
		line("#### Jobs\n\n| | Job | |\n| :-: | --- | --- |\n%s\n", strings.Join(rows, "\n"))
	}

	if warnings > 0 {
		line("#### Release notes warnings\n")
		findings(&b, p.File, p.Findings)
		for _, e := range p.Edits {
			findings(&b, e.File, e.Findings)
		}
	}

	if len(s.Assets) > 0 {
		// Before publication, the assets are only a workflow artifact, which downloads as one zip.
		released := published && p != nil && p.Tag != ""
		line("#### Assets\n")
		if !released && s.Archive != "" {
			line("[Download all (zip)](%s): a workflow artifact, for signed-in users who can read this repository, until it expires.\n", s.Archive)
		}
		line("| File | Size |\n| --- | ---: |")
		for _, a := range s.Assets {
			name := "`" + a.Name + "`"
			if released {
				name = fmt.Sprintf("[%s](%s/%s/releases/download/%s/%s)", name, s.Server, s.Repository, p.Tag, url.PathEscape(a.Name))
			}
			line("| %s | %s |", name, size(a.Size))
		}
		line("")
	}

	if p != nil {
		for _, w := range p.Warnings {
			line("⚠️ %s\n", w)
		}
		if p.Tag != "" && !s.Merged && s.Failed() == "" && s.Jobs["validate"].Outputs["build"] != "true" {
			line("Release checks and assets run after the merge, because this pull request comes from a fork.\n")
		}
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}

func (s Status) details(run []publish.RunJob, name, fallback string) string {
	return fmt.Sprintf("[Details](%s)", jobURL(run, name, fallback))
}

// jobURL returns the page of the run's job with the name, or of a job of the reusable
// workflow that job calls, whose jobs are named like "release-assets / build", or fallback
// when the run has none. Jobs only count from the latest attempt that lists any of them:
// GitHub names a calling job alone in an attempt that skips it, and by its called jobs in one
// that runs them, so after Re-run failed jobs an earlier attempt's job can stand under the
// other name. Of the called jobs, the first that failed or was cancelled shows why the row
// did, and otherwise the first.
func jobURL(run []publish.RunJob, name, fallback string) string {
	var latest []publish.RunJob
	for _, j := range run {
		switch {
		case (j.Name != name && !strings.HasPrefix(j.Name, name+" / ")) || j.URL == "":
		case len(latest) == 0 || j.RunAttempt > latest[0].RunAttempt:
			latest = []publish.RunJob{j}
		case j.RunAttempt == latest[0].RunAttempt:
			latest = append(latest, j)
		}
	}
	if len(latest) == 0 {
		return fallback
	}
	if i := slices.IndexFunc(latest, func(j publish.RunJob) bool { return j.Conclusion == "failure" || j.Conclusion == "cancelled" }); i >= 0 {
		return latest[i].URL
	}
	return latest[0].URL
}

func plural(n int, word string) string {
	if n == 1 {
		return word
	}
	return word + "s"
}

func findings(b *strings.Builder, file string, found []notes.Finding) {
	if len(found) == 0 {
		return
	}
	fmt.Fprintf(b, "`%s` breaks these rules. They don't block merging; fix them if they're mistakes.\n\n", file)
	for _, f := range found {
		fmt.Fprintf(b, "- %s\n", f.String())
	}
	b.WriteString("\n")
}

func short(sha string) string {
	if len(sha) > 7 {
		return sha[:7]
	}
	return sha
}

func size(n int64) string {
	switch {
	case n >= 1<<20:
		return fmt.Sprintf("%.1f MiB", float64(n)/(1<<20))
	case n >= 1<<10:
		return fmt.Sprintf("%.1f KiB", float64(n)/(1<<10))
	}
	return fmt.Sprintf("%d B", n)
}

// ErrSuperseded says a pull request run's report was skipped because a newer commit or the
// merge has replaced what the run checked.
var ErrSuperseded = errors.New("the pull request has moved on from the commit this run checked")

// Update writes the blocks into the pull request's description, and reports whether it
// changed the description. It adds missing blocks, the summary at the start and the status at
// the end, only if create is true or the description already has one, and never changes the
// text outside the blocks. Empty blocks leave a description without blocks alone, and say
// existing ones are out of date. A pull request run passes the head commit it checked, and
// writes nothing, returning ErrSuperseded, once the pull request has a newer head or is
// merged or closed, so a slow run can't replace a newer run's status.
func Update(ctx context.Context, gh *publish.GitHub, number int, head string, blocks Blocks, create bool) (bool, error) {
	// Read the description just before writing it, so a maintainer's edit is less likely to be lost.
	d, err := gh.PullRequestDescription(ctx, number)
	if err != nil {
		return false, err
	}
	if head != "" && (d.Head != head || !d.Open) {
		return false, ErrSuperseded
	}
	body := d.Body
	found := strings.Contains(body, SummaryStart) || strings.Contains(body, StatusStart)
	switch {
	case !found && (blocks == Blocks{} || !create):
		return false, nil
	case blocks == Blocks{}:
		blocks.Summary = "This pull request no longer requests a release or edits release notes.\n"
	}
	updated := splice(body, blocks)
	if updated == body {
		return false, nil
	}
	return true, gh.UpdatePullRequestBody(ctx, number, updated)
}

// splice returns body with each block's content replaced, or with a missing summary inserted
// at the start and a missing status appended at the end, each a blank line from the rest. A
// start marker without its end marker no longer bounds any text the report owns, so splice
// removes just that marker and adds a new block, keeping the old text: a maintainer's text
// might follow the marker.
func splice(body string, blocks Blocks) string {
	body = dropUnclosed(body, SummaryStart, SummaryEnd)
	body = dropUnclosed(body, StatusStart, StatusEnd)

	summary := SummaryStart + "\n" + blocks.Summary + SummaryEnd
	if i := strings.Index(body, SummaryStart); i >= 0 {
		j := i + len(SummaryStart) + strings.Index(body[i+len(SummaryStart):], SummaryEnd)
		body = body[:i] + summary + body[j+len(SummaryEnd):]
	} else {
		body = summary + "\n\n" + body
	}

	status := StatusStart + "\n" + blocks.Status + StatusEnd
	if i := strings.Index(body, StatusStart); i >= 0 {
		j := i + len(StatusStart) + strings.Index(body[i+len(StatusStart):], StatusEnd)
		return body[:i] + status + body[j+len(StatusEnd):]
	}
	switch {
	case strings.HasSuffix(body, "\n\n") || strings.HasSuffix(body, "\r\n\r\n"):
	case strings.HasSuffix(body, "\n"):
		body += "\n"
	default:
		body += "\n\n"
	}
	return body + status
}

// dropUnclosed removes the start marker from body if no end marker follows it.
func dropUnclosed(body, start, end string) string {
	i := strings.Index(body, start)
	if i < 0 || strings.Contains(body[i+len(start):], end) {
		return body
	}
	return body[:i] + body[i+len(start):]
}

// Failure writes the comment that tells whoever merged the pull request which job failed, or
// returns "" before the merge or when nothing failed. GitHub doesn't notify anyone mentioned
// in an edited description, so this comment is the notification.
func Failure(s Status) string {
	failed := s.Failed()
	if !s.Merged || failed == "" {
		return ""
	}
	mention := ""
	if s.MergedBy != "" {
		mention = "@" + s.MergedBy + " "
	}
	clauses := s.failedJobs("The release's", bold)
	what := strings.Join(clauses, ", and ")
	if len(clauses) > 1 {
		// Sets "in this workflow run" apart from the last clause, so it reads as about them all.
		what += ","
	}
	return fmt.Sprintf("%s\n%s%s in [this workflow run](%s). The pull request description has the details and how to retry.\n",
		failureMarker(s, failed), mention, what, s.RunURL)
}

// failureMarker identifies a failure comment by the run attempt and job it reports.
func failureMarker(s Status, job string) string {
	return fmt.Sprintf("%srun=%s attempt=%s job=%s -->", failurePrefix, s.RunID, s.RunAttempt, job)
}

const failurePrefix = "<!-- release-planner:failure "

// Notify posts the Failure comment on the pull request, unless there's nothing to report or
// the latest failure comment already reports the same run attempt and job, and reports
// whether it posted.
func Notify(ctx context.Context, gh *publish.GitHub, number int, s Status) (bool, error) {
	comment := Failure(s)
	if comment == "" {
		return false, nil
	}
	comments, err := gh.Comments(ctx, number)
	if err != nil {
		return false, err
	}
	for i := len(comments) - 1; i >= 0; i-- {
		if strings.Contains(comments[i].Body, failurePrefix) {
			if strings.Contains(comments[i].Body, failureMarker(s, s.Failed())) {
				return false, nil
			}
			break
		}
	}
	return true, gh.CreateComment(ctx, number, comment)
}
