package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/fabricahq/release-planner/internal/plan"
	"github.com/fabricahq/release-planner/internal/publish"
)

func writePlan(t *testing.T, p plan.Plan) string {
	t.Helper()
	data, err := json.Marshal(p)
	if err != nil {
		t.Fatal(err)
	}
	file := filepath.Join(t.TempDir(), "release-plan.json")
	if err := os.WriteFile(file, data, 0o644); err != nil {
		t.Fatal(err)
	}
	return file
}

const merged = "dddddddddddddddddddddddddddddddddddddddd"

func TestReportWritesTheStatusInTheDescription(t *testing.T) {
	output := actionsFiles(t)
	t.Setenv("GITHUB_RUN_ID", "100")
	description := "Why v1.2.0? Minor: adds the --shout flag.\r\n"
	api := newAPI(t, map[string]any{
		"GET /pulls/7":               map[string]any{"body": description},
		"PATCH /pulls/7":             map[string]any{},
		"GET /actions/runs/100/jobs": map[string]any{"jobs": []any{map[string]any{"name": "validate", "conclusion": "success", "run_attempt": 1, "html_url": "https://github.com/fabricahq/example/actions/runs/100/job/5"}}},
	})
	file := writePlan(t, plan.Plan{Tag: "v1.2.0", Commit: strings.Repeat("a", 40), Previous: "v1.1.0", File: "_releases/v1.2.0.md"})
	needs := `{"validate":{"result":"success","outputs":{"tag":"v1.2.0","build":"true"}},"publish":{"result":"skipped","outputs":{}}}`
	code, out, errOut := cli(t, "report", "--needs", needs, "--branch", "main", "--pull-request", "7", "--head-ref", "release-v1.2.0", "--head-repository", "fabricahq/example",
		"--plan", file, "--assets", filepath.Join(t.TempDir(), "none"))
	if code != 0 || !strings.Contains(out, "Updated the release status in the description of #7") {
		t.Fatalf("%d %s %s", code, out, errOut)
	}
	var sent struct{ Body string }
	if err := json.Unmarshal([]byte(api.sent("PATCH /pulls/7")), &sent); err != nil ||
		!strings.HasPrefix(sent.Body, "<!-- release-planner:summary:start -->\n**[✏️ Edit the v1.2.0 release notes](https://github.com/fabricahq/example/edit/release-v1.2.0/_releases/v1.2.0.md)**\n\n**When you merge this PR:**\n") ||
		!strings.Contains(sent.Body, "\n<!-- release-planner:summary:end -->\n\n"+description+"\n<!-- release-planner:status:start -->\n#### Jobs\n") ||
		!strings.Contains(sent.Body, "| ✅ | Check the version and release notes | [Details](https://github.com/fabricahq/example/actions/runs/100/job/5) |") ||
		!strings.Contains(sent.Body, "published with these release notes and the release assets.") ||
		!strings.HasSuffix(sent.Body, "| ⏸️ | Publish | Runs when you merge |\n\n> Generated by [Release Planner](https://release-planner.fabricahq.com)\n<!-- release-planner:status:end -->") {
		t.Fatal(sent.Body, err)
	}
	if summary := output("summary"); !strings.HasPrefix(summary, "**[✏️ Edit the v1.2.0 release notes]") || !strings.Contains(summary, "(https://github.com/fabricahq/example/releases/tag/v1.1.0) |\n\n#### Jobs\n") || strings.Contains(summary, "release-planner:") {
		t.Fatal(summary)
	}
	if strings.Contains(strings.Join(api.requests, " "), "comments") {
		t.Fatal("commented on an open pull request", api.requests)
	}

	// A run for an older head leaves the newer run's status alone.
	api = newAPI(t, map[string]any{"GET /pulls/7": map[string]any{"body": description, "state": "open", "head": map[string]string{"sha": strings.Repeat("d", 40)}}})
	code, out, errOut = cli(t, "report", "--needs", needs, "--branch", "main", "--pull-request", "7", "--head-sha", strings.Repeat("c", 40), "--plan", file)
	if code != 0 || !strings.Contains(out, "Left the description of #7 alone") || strings.Contains(strings.Join(api.requests, " "), "PATCH") {
		t.Fatalf("%d %s %s %v", code, out, errOut, api.requests)
	}

	// Without a plan, a failure on a pull request isn't taken for a release.
	api = newAPI(t, map[string]any{"GET /pulls/7": map[string]any{"body": "Fix a typo"}})
	missing := filepath.Join(t.TempDir(), "release-plan.json")
	if code, _, errOut := cli(t, "report", "--needs", `{"validate":{"result":"failure"}}`, "--branch", "main", "--pull-request", "7", "--plan", missing); code != 0 || strings.Join(api.requests, " ") != "GET /actions/runs/100/jobs GET /pulls/7" {
		t.Fatalf("%d %s %v", code, errOut, api.requests)
	}
}

// Before publication, the assets link to the zip of the run that built them, when the
// Actions API names that artifact.
func TestReportLinksTheAssetsArtifact(t *testing.T) {
	actionsFiles(t)
	assets := t.TempDir()
	if err := os.WriteFile(filepath.Join(assets, "tool.tar.gz"), []byte("tool"), 0o644); err != nil {
		t.Fatal(err)
	}
	file := writePlan(t, plan.Plan{Tag: "v1.2.0", Commit: strings.Repeat("a", 40), BuildRun: 77})
	// The link is to the artifact attest bound, never another upload under the same name.
	needs := `{"validate":{"result":"success","outputs":{"build":"true"}},"attest":{"result":"success","outputs":{"assets-artifact":"9"}},"publish":{"result":"skipped","outputs":{}}}`
	for name, c := range map[string]struct {
		artifacts any
		want      string
	}{
		"found":    {map[string]any{"artifacts": []any{map[string]any{"id": 8, "name": "release-assets", "expired": false}, map[string]any{"id": 9, "name": "release-assets", "expired": false}}}, "[Download all (zip)](https://github.com/fabricahq/example/actions/runs/77/artifacts/9)"},
		"replaced": {map[string]any{"artifacts": []any{map[string]any{"id": 8, "name": "release-assets", "expired": false}}}, ""},
		"expired":  {map[string]any{"artifacts": []any{map[string]any{"id": 9, "name": "release-assets", "expired": true}}}, ""},
		"denied":   {status{403, map[string]string{"message": "no"}}, ""},
	} {
		t.Run(name, func(t *testing.T) {
			api := newAPI(t, map[string]any{"GET /actions/runs/77/artifacts": c.artifacts, "GET /pulls/7": map[string]any{"body": ""}, "PATCH /pulls/7": map[string]any{}})
			if code, out, errOut := cli(t, "report", "--needs", needs, "--branch", "main", "--pull-request", "7", "--plan", file, "--assets", assets); code != 0 {
				t.Fatalf("%d %s %s", code, out, errOut)
			}
			body := api.sent("PATCH /pulls/7")
			if !strings.Contains(body, "| `tool.tar.gz` | 4 B |") || strings.Contains(body, "Download all") != (c.want != "") || !strings.Contains(body, c.want) {
				t.Fatal(body)
			}
		})
	}
}

// After the merge, a failure is reported in the merged pull request's description and in a
// comment to whoever merged it, even when validation failed before it named the pull request.
func TestReportMentionsWhoMergedAFailedRelease(t *testing.T) {
	actionsFiles(t)
	t.Setenv("GITHUB_RUN_ID", "100")
	t.Setenv("GITHUB_RUN_ATTEMPT", "2")
	old := "Intro\n\n<!-- release-planner:status:start -->\nold\n<!-- release-planner:status:end -->\n\nHuman footer"
	api := newAPI(t, map[string]any{
		"GET /commits/" + merged + "/pulls": []any{map[string]any{"number": 2, "merged_at": "2026-09-25T12:00:00Z", "merge_commit_sha": merged, "base": map[string]string{"ref": "main"}}},
		"GET /pulls/2":                      map[string]any{"head": map[string]any{"sha": strings.Repeat("c", 40)}, "merged_by": map[string]string{"login": "mona"}, "body": old},
		"PATCH /pulls/2":                    map[string]any{},
		"GET /issues/2/comments":            []any{map[string]any{"id": 5, "body": "<!-- release-planner:failure run=100 attempt=1 job=validate -->\n@mona earlier"}},
		"POST /issues/2/comments":           map[string]any{},
	})
	needs := `{"validate":{"result":"failure","outputs":{}},"publish":{"result":"skipped","outputs":{}}}`
	code, out, errOut := cli(t, "report", "--needs", needs, "--branch", "main", "--merged", merged, "--plan", filepath.Join(t.TempDir(), "missing.json"))
	if code != 0 || !strings.Contains(out, "Commented on #2 about the failed validate job.") {
		t.Fatalf("%d %s %s", code, out, errOut)
	}
	var edit, comment struct{ Body string }
	_ = json.Unmarshal([]byte(api.sent("PATCH /pulls/2")), &edit)
	_ = json.Unmarshal([]byte(api.sent("POST /issues/2/comments")), &comment)
	if !strings.HasPrefix(edit.Body, "<!-- release-planner:summary:start -->\n❌ **The validate job failed.**") ||
		!strings.Contains(edit.Body, "<!-- release-planner:summary:end -->\n\nIntro\n\n<!-- release-planner:status:start -->\n#### Jobs\n") ||
		!strings.HasSuffix(edit.Body, "<!-- release-planner:status:end -->\n\nHuman footer") || strings.Contains(edit.Body, "@mona") {
		t.Fatal(edit.Body)
	}
	if !strings.HasPrefix(comment.Body, "<!-- release-planner:failure run=100 attempt=2 job=validate -->\n@mona The release's **validate** job failed in [this workflow run](https://github.com/fabricahq/example/actions/runs/100).") {
		t.Fatal(comment.Body)
	}
}

// A fork's pull request can't be edited; the report still succeeds.
func TestReportDegradesWithoutWriteAccess(t *testing.T) {
	actionsFiles(t)
	newAPI(t, map[string]any{"GET /pulls/7": map[string]any{"body": ""}, "PATCH /pulls/7": status{403, map[string]string{"message": "Resource not accessible by integration"}}})
	file := writePlan(t, plan.Plan{Tag: "v1.2.0", Commit: strings.Repeat("a", 40)})
	code, out, errOut := cli(t, "report", "--needs", `{"validate":{"result":"success","outputs":{}}}`, "--branch", "main", "--pull-request", "7", "--plan", file)
	if code != 0 || !strings.Contains(out, "::warning title=Release status::Couldn't update the release status in the description of #7") {
		t.Fatalf("%d %s %s", code, out, errOut)
	}
}

func TestDispatchStartsEachTargetWithTheRelease(t *testing.T) {
	output := actionsFiles(t)
	api := newAPI(t, map[string]any{
		"GET /repos/fabricahq/homebrew-tap":                                          map[string]string{"default_branch": "main"},
		"POST /repos/fabricahq/homebrew-tap/actions/workflows/update.yml/dispatches": status{204, nil},
	})
	code, out, errOut := cli(t, "dispatch", "--tag", "v1.2.0", "--target", "fabricahq/homebrew-tap:update.yml", "--target", "fabricahq/scoop-bucket:update.yml")
	if code != 1 || !strings.Contains(out, "Started update.yml in fabricahq/homebrew-tap for v1.2.0") || !strings.Contains(errOut, "1 of 2 post-publish workflows didn't start; v1.2.0 is published either way") {
		t.Fatalf("%d %s %s", code, out, errOut)
	}
	var sent struct {
		Ref    string
		Inputs map[string]string
	}
	if err := json.Unmarshal([]byte(api.sent("POST /repos/fabricahq/homebrew-tap/actions/workflows/update.yml/dispatches")), &sent); err != nil ||
		sent.Ref != "main" || sent.Inputs["tag"] != "v1.2.0" || sent.Inputs["version"] != "1.2.0" {
		t.Fatal(sent, err)
	}
	if !strings.Contains(out, "::error title=Post-publish::") || !strings.Contains(out, "fabricahq/scoop-bucket") || output("output") != "" {
		t.Fatalf("%s %q", out, output("output"))
	}
}

// Each post-publish workflow runs in its own job, which the report links at its latest attempt.
func TestReportListsEachPostPublishWorkflow(t *testing.T) {
	actionsFiles(t)
	t.Setenv("GITHUB_RUN_ID", "100")
	job := func(name, conclusion string, attempt, id int) map[string]any {
		return map[string]any{"name": name, "conclusion": conclusion, "run_attempt": attempt, "html_url": fmt.Sprintf("https://github.com/fabricahq/example/actions/runs/100/job/%d", id)}
	}
	api := newAPI(t, map[string]any{
		"GET /actions/runs/100/jobs": map[string]any{"jobs": []any{
			job("publish", "success", 1, 1),
			job("post-publish (fabricahq/homebrew-tap:update.yml)", "success", 1, 2),
			job("post-publish (deploy.yml) / deploy", "failure", 1, 3),
			job("post-publish (fabricahq/winget:update.yml)", "failure", 1, 4),
			job("post-publish (fabricahq/winget:update.yml)", "success", 2, 5),
		}},
		"GET /actions/runs/77/jobs": map[string]any{"jobs": []any{job("validate", "success", 1, 76), job("release-assets / build", "success", 1, 77)}},
		"GET /pulls/2":              map[string]any{"body": "Release v1.2.0"},
		"PATCH /pulls/2":            map[string]any{},
		"GET /issues/2/comments":    []any{},
		"POST /issues/2/comments":   map[string]any{},
	})
	file := writePlan(t, plan.Plan{Tag: "v1.2.0", Commit: strings.Repeat("a", 40), PullRequest: 2, BuildRun: 77, Reused: true})
	needs := `{"validate":{"result":"success","outputs":{}},"release-assets":{"result":"skipped","outputs":{}},"publish":{"result":"success","outputs":{}},` +
		`"post-publish-1":{"result":"success","outputs":{}},"post-publish-2":{"result":"failure","outputs":{}},"post-publish-3":{"result":"success","outputs":{}}}`
	hooks := `[{"job":"post-publish-1","name":"post-publish (fabricahq/homebrew-tap:update.yml)","when":"post-publish","workflow":"update.yml","repository":"fabricahq/homebrew-tap"},` +
		`{"job":"post-publish-2","name":"post-publish (deploy.yml)","when":"post-publish","workflow":"deploy.yml","title":"Deploy"},` +
		`{"job":"post-publish-3","name":"post-publish (fabricahq/winget:update.yml)","when":"post-publish","workflow":"update.yml","repository":"fabricahq/winget"}]`
	if code, out, errOut := cli(t, "report", "--needs", needs, "--branch", "main", "--merged", merged, "--plan", file, "--hooks", hooks); code != 0 {
		t.Fatalf("%d %s %s", code, out, errOut)
	}
	body := api.sent("PATCH /pulls/2")
	if !strings.Contains(api.sent("POST /issues/2/comments"), "**post-publish (deploy.yml)** job failed") {
		t.Fatal(api.requests)
	}
	for _, want := range []string{
		"✅ Published [v1.2.0]",
		"| ♻️ | Build the release assets | [Reused from the pull request](https://github.com/fabricahq/example/actions/runs/100/job/77) |",
		"| ✅ | Publish | [Details](https://github.com/fabricahq/example/actions/runs/100/job/1) |",
		"| ✅ | Run fabricahq/homebrew-tap `update.yml` | [Details](https://github.com/fabricahq/example/actions/runs/100/job/2) |",
		"| ❌ | Deploy | [Details](https://github.com/fabricahq/example/actions/runs/100/job/3) |",
		"| ✅ | Run fabricahq/winget `update.yml` | [Details](https://github.com/fabricahq/example/actions/runs/100/job/5) |",
	} {
		if !strings.Contains(body, want) {
			t.Fatalf("lacks %q:\n%s", want, body)
		}
	}
	if code, _, errOut := cli(t, "report", "--needs", needs, "--branch", "main", "--merged", merged, "--plan", file, "--hooks", "post-publish"); code != 1 || !strings.Contains(errOut, "--hooks") {
		t.Fatal(errOut)
	}
}

// sandboxJobs are the jobs of release run 36933131243 in
// fabricahq/release-planner-pre-publish-sandbox, as the Actions API lists them with
// filter=all, through the attempt. In attempt 1, warm-caches.yml failed, so publish and the
// post-publish jobs were skipped; a skipped job that calls a workflow is listed by its own
// name. After Re-run failed jobs, attempt 2 ran deploy.yml, listed by its called job
// "post-publish (deploy.yml) / run", which failed, and attempt 3 ran it again. Each attempt
// copies the jobs that succeeded before with new IDs.
func sandboxJobs(attempt int) []any {
	var jobs []any
	for _, j := range []struct {
		id, attempt     int
		name, concluded string
	}{
		{110607041269, 1, "validate", "success"},
		{110607321965, 1, "pre-publish (warm-caches.yml) / run", "failure"},
		{110607321993, 1, "pre-publish (migrate-database.yml) / migrate", "success"},
		{110607378940, 1, "report", "success"},
		{110607379813, 1, "publish", "skipped"},
		{110607380382, 1, "post-publish (deploy.yml)", "skipped"},
		{110607380500, 1, "post-publish (fabricahq/release-planner-sandbox:update.yml)", "skipped"},
		{110607835554, 2, "pre-publish (warm-caches.yml) / run", "success"},
		{110607835573, 2, "validate", "success"},
		{110607836789, 2, "pre-publish (migrate-database.yml) / migrate", "success"},
		{110607905494, 2, "publish", "success"},
		{110608183369, 2, "post-publish (fabricahq/release-planner-sandbox:update.yml)", "failure"},
		{110608183785, 2, "post-publish (deploy.yml) / run", "failure"},
		{110608244983, 2, "report", "success"},
		{110608819989, 3, "validate", "success"},
		{110608821335, 3, "pre-publish (migrate-database.yml) / migrate", "success"},
		{110608822213, 3, "post-publish (fabricahq/release-planner-sandbox:update.yml)", "failure"},
		{110608822302, 3, "pre-publish (warm-caches.yml) / run", "success"},
		{110608822417, 3, "post-publish (deploy.yml) / run", "success"},
		{110608822796, 3, "publish", "success"},
		{110608883630, 3, "report", "success"},
	} {
		if j.attempt <= attempt {
			jobs = append(jobs, map[string]any{"name": j.name, "conclusion": j.concluded, "run_attempt": j.attempt,
				"html_url": fmt.Sprintf("https://github.com/fabricahq/example/actions/runs/100/job/%d", j.id)})
		}
	}
	return jobs
}

// After Re-run failed jobs, each hook's row links to its job in the latest attempt that ran
// it, not to the job an earlier attempt skipped, as in the sandbox's release run.
func TestReportLinksEachHookAtTheLatestAttempt(t *testing.T) {
	actionsFiles(t)
	t.Setenv("GITHUB_RUN_ID", "100")
	hooks := `[{"job":"pre-publish-1","name":"pre-publish (migrate-database.yml)","when":"pre-publish","workflow":"migrate-database.yml","title":"Migrate the database"},` +
		`{"job":"pre-publish-2","name":"pre-publish (warm-caches.yml)","when":"pre-publish","workflow":"warm-caches.yml","title":"Warm the caches"},` +
		`{"job":"post-publish-1","name":"post-publish (deploy.yml)","when":"post-publish","workflow":"deploy.yml","title":"Deploy"},` +
		`{"job":"post-publish-2","name":"post-publish (fabricahq/release-planner-sandbox:update.yml)","when":"post-publish","workflow":"update.yml","repository":"fabricahq/release-planner-sandbox"}]`
	file := writePlan(t, plan.Plan{Tag: "v0.14.0", Commit: strings.Repeat("a", 40), PullRequest: 2})
	for _, tc := range []struct {
		attempt int
		deploy  string
		want    []string
	}{
		{2, "failure", []string{
			"| ❌ | Deploy | [Details](https://github.com/fabricahq/example/actions/runs/100/job/110608183785) |",
			"| ❌ | Run fabricahq/release-planner-sandbox `update.yml` | [Details](https://github.com/fabricahq/example/actions/runs/100/job/110608183369) |",
		}},
		{3, "success", []string{
			"| ✅ | Deploy | [Details](https://github.com/fabricahq/example/actions/runs/100/job/110608822417) |",
			"| ❌ | Run fabricahq/release-planner-sandbox `update.yml` | [Details](https://github.com/fabricahq/example/actions/runs/100/job/110608822213) |",
		}},
	} {
		t.Run(fmt.Sprintf("attempt %d", tc.attempt), func(t *testing.T) {
			t.Setenv("GITHUB_RUN_ATTEMPT", fmt.Sprint(tc.attempt))
			api := newAPI(t, map[string]any{
				"GET /actions/runs/100/jobs": map[string]any{"jobs": sandboxJobs(tc.attempt)},
				"GET /pulls/2":               map[string]any{"body": "Why v0.14.0? End-to-end test."},
				"PATCH /pulls/2":             map[string]any{},
				"GET /issues/2/comments":     []any{},
				"POST /issues/2/comments":    map[string]any{},
			})
			needs := `{"validate":{"result":"success","outputs":{}},"pre-publish-1":{"result":"success","outputs":{}},"pre-publish-2":{"result":"success","outputs":{}},` +
				`"publish":{"result":"success","outputs":{}},"post-publish-1":{"result":"` + tc.deploy + `","outputs":{}},"post-publish-2":{"result":"failure","outputs":{}}}`
			if code, out, errOut := cli(t, "report", "--needs", needs, "--branch", "main", "--merged", merged, "--plan", file, "--hooks", hooks); code != 0 {
				t.Fatalf("%d %s %s", code, out, errOut)
			}
			body := api.sent("PATCH /pulls/2")
			for _, want := range append(tc.want,
				"| ✅ | Migrate the database | [Details](https://github.com/fabricahq/example/actions/runs/100/job/110608821335) |",
				"| ✅ | Warm the caches | [Details](https://github.com/fabricahq/example/actions/runs/100/job/110608822302) |",
				"| ✅ | Publish | [Details](https://github.com/fabricahq/example/actions/runs/100/job/110608822796) |",
			) {
				if tc.attempt == 2 {
					// Attempt 2 copied migrate-database.yml and ran the rest itself.
					want = strings.NewReplacer("110608821335", "110607836789", "110608822302", "110607835554", "110608822796", "110607905494").Replace(want)
				}
				if !strings.Contains(body, want) {
					t.Errorf("lacks %q:\n%s", want, body)
				}
			}
			if strings.Contains(body, "110607380382") {
				t.Errorf("links attempt 1's skipped deploy.yml job:\n%s", body)
			}
		})
	}
}

// A prerelease starts only the post-publish workflows that opt in.
func TestDispatchSkipsPrereleasesUnlessTheyOptIn(t *testing.T) {
	output := actionsFiles(t)
	api := newAPI(t, map[string]any{
		"GET /repos/fabricahq/homebrew-tap":                                          map[string]string{"default_branch": "main"},
		"POST /repos/fabricahq/homebrew-tap/actions/workflows/update.yml/dispatches": status{204, nil},
	})
	code, out, _ := cli(t, "dispatch", "--tag", "v1.2.0-rc.1", "--target", "fabricahq/homebrew-tap:update.yml")
	if code != 0 || !strings.Contains(out, "prerelease") || len(api.requests) != 0 || output("output") != "" {
		t.Fatalf("%d %s %v %q", code, out, api.requests, output("output"))
	}
	if code, out, errOut := cli(t, "dispatch", "--tag", "v1.2.0-rc.1", "--target", "fabricahq/homebrew-tap:update.yml", "--prereleases"); code != 0 || !strings.Contains(out, "Started update.yml in fabricahq/homebrew-tap for v1.2.0-rc.1") {
		t.Fatalf("%d %s %s", code, out, errOut)
	}
	if code, _, errOut := cli(t, "dispatch", "--tag", "v1.2.0", "--target", "homebrew-tap"); code != 1 || !strings.Contains(errOut, "owner/name:workflow.yml") {
		t.Fatal(errOut)
	}
	// The old command name is gone.
	if code, _, errOut := cli(t, "downstream", "--tag", "v1.2.0"); code != 2 || !strings.Contains(errOut, `unknown command "downstream"`) {
		t.Fatal(code, errOut)
	}
}

// fakeGH puts a gh on PATH that passes attestation checks except for files named bad*, and
// logs its arguments.
func fakeGH(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	log := filepath.Join(dir, "log")
	script := "#!/bin/sh\necho \"$@\" >> " + log + "\ncase \"$3\" in */bad*) echo 'no attestation'; exit 1;; esac\n"
	if err := os.WriteFile(filepath.Join(dir, "gh"), []byte(script), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", dir+string(os.PathListSeparator)+os.Getenv("PATH"))
	return log
}

// Publish refuses a build run that planned another release, and assets without an
// attestation from the Release workflow, before it writes anything.
func TestPublishChecksTheBuildBeforeWriting(t *testing.T) {
	api := newAPI(t, map[string]any{})
	p := plan.Plan{Tag: "v1.2.0", Commit: strings.Repeat("a", 40), Notes: "Notes", Head: strings.Repeat("c", 40), Merged: merged, PullRequest: 2}
	file := writePlan(t, p)
	other := p
	other.Commit = strings.Repeat("b", 40)
	code, _, errOut := cli(t, "publish", "--plan", file, "--built-plan", writePlan(t, other), "--branch", "main")
	if code != 1 || !strings.Contains(errOut, "the run that checked and built the release planned") {
		t.Fatal(errOut)
	}

	log := fakeGH(t)
	assets := t.TempDir()
	for _, name := range []string{"good.tar.gz", "bad.tar.gz"} {
		if err := os.WriteFile(filepath.Join(assets, name), []byte(name), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	code, _, errOut = cli(t, "publish", "--plan", file, "--built-plan", file, "--branch", "main", "--assets", assets, "--signer-workflow", ".github/workflows/release-planner.yml")
	if code != 1 || !strings.Contains(errOut, "bad.tar.gz has no build attestation from .github/workflows/release-planner.yml in fabricahq/example") || len(api.requests) != 0 {
		t.Fatalf("%d %s %v", code, errOut, api.requests)
	}
	data, _ := os.ReadFile(log)
	if !strings.Contains(string(data), "attestation verify "+filepath.Join(assets, "bad.tar.gz")+" --repo fabricahq/example --signer-workflow fabricahq/example/.github/workflows/release-planner.yml --deny-self-hosted-runners") {
		t.Fatal(string(data))
	}
}

// publish's outputs tell the report what it did: whether the release was new, and which
// edited notes changed.
func TestPublishOutputsWhatItDid(t *testing.T) {
	for name, tc := range map[string]struct {
		p    plan.Plan
		res  publish.Result
		want string
	}{
		"published":         {plan.Plan{Tag: "v1.2.0"}, publish.Result{}, "release=published\nnotes=[]\n"},
		"already published": {plan.Plan{Tag: "v1.2.0"}, publish.Result{AlreadyPublished: true}, "release=already-published\nnotes=[]\n"},
		"edits": {plan.Plan{Edits: []plan.Edit{{Tag: "v1.0.0"}, {Tag: "v1.1.0"}}}, publish.Result{Edited: []publish.Edited{{Tag: "v1.0.0"}, {Tag: "v1.1.0", Changed: true}}},
			`release=` + "\n" + `notes=[{"tag":"v1.0.0","changed":false},{"tag":"v1.1.0","changed":true}]` + "\n"},
	} {
		t.Run(name, func(t *testing.T) {
			if got := publishOutputs(tc.p, tc.res); got != tc.want {
				t.Fatalf("got %q, want %q", got, tc.want)
			}
		})
	}
}
